### ISSUE TITLE
caffeCoder very slow

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/himrep#18]
Hi @GiuliaP and @pattacini,

@maxime-petit and I have just setup a new computer with a Tesla K40 in order to speed up the object recognition on the iCub. Previously, `caffeCoder` was slow on another machine (also using the K40) which had a much slower CPU. The new computer has a fast CPU and has no power consuming modules running besides `caffeCoder`.

Unfortunately, a forward pass with the Tesla takes around 300ms; roughly the same time as using CPU only. We use CUDA 7.5 with cuDNN v4. Changing `double` to `float` results in roughly double the speed (nice word play, isn't it?), which is still much slower than the 10ms reported in https://github.com/robotology/himrep/pull/10.

Do you have any idea how to speed up `caffeCoder`?

It seems like generally the GPU is running fast, e.g. running `./build/tools/caffe time -model examples/mnist/lenet_train_test.prototxt -gpu 0` results in `Total Time: 161.843 ms.` compared to the CPU only version (`./build/tools/caffe time -model examples/mnist/lenet_train_test.prototxt`) which results in `Total Time: 4249 ms.`.

Some debugging has shown that the function which takes a long time is `FowardPrefilled` (just `Forward` takes the same time, see https://github.com/robotology/himrep/pull/17).

It would be great if we can figure this out somehow :).

Best,
Tobi and @maxime-petit

**Comment by Tobias-Fischer** [comment]
Forgot the log file:

[log_icubunicorn_caffeCoder_24775.txt](https://github.com/robotology/himrep/files/250838/log_icubunicorn_caffeCoder_24775.txt)

**Comment by GiuliaP** [comment]
Hi @Tobias-Fischer , 

I am aware of issues like the deprecation of `ForwardPrefilled` and the fact that using `double` precision may not be necessary. I'm going to fix both of these, verifying that replacing with `Forward` does not affect the correctness of feature extraction.

Regarding this issue, it is very strange that it takes so long on a K40, but surely we will figure it out. I have looked at the log and at a first glance I do not notice anything strange (apart the `300ms` time). I will perform the same test as yours (`./build/tools/caffe time -model examples/mnist/lenet_train_test.prototxt -gpu 0`) to check that the same code runs in the same time on our systems. 

Could you attach the output of the `cmake ../` command when you configure `caffe` to check which libraries are you using?

Eventually, I can also provide you with a simple code to extract features offline, so that it would be easier to debug the problem, without the need of the robot.

**Comment by maxime-petit** [comment]
Hi @GiuliaP ,

You will find the output of the CMake ../ command of Caffe as well as the related CMakeCache
 in attachment. Happy to receive the code to extract the features offline :) Let us know if we need to do some precise tests here. Thanks!

./Max

cc: @Tobias-Fischer 

[CMakeCache_Caffe_London.txt](https://github.com/robotology/himrep/files/251894/CMakeCache_Caffe_London.txt)

[CMake_Caffe_Output_London.txt](https://github.com/robotology/himrep/files/251905/CMake_Caffe_Output_London.txt)

**Comment by Tobias-Fischer** [comment]
Hi @GiuliaP,
here the proper output of cmake:

```
icub@icubunicorn:~/robot/tools/caffe/build$ cmake ..
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Found PROTOBUF Compiler: /usr/bin/protoc
-- Found lmdb    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/liblmdb.so)
-- Found LevelDB (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libleveldb.so)
-- Found Snappy  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libsnappy.so)
-- CUDA detected: 7.5
-- Found cuDNN: ver. 4.0.7 found (include: /usr/include/x86_64-linux-gnu, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Added CUDA NVCC flags for: sm_35 sm_21
-- OpenCV found (/home/icub/robot/tools/opencv/build)
-- Found Atlas (include: /usr/include, library: /usr/lib/libatlas.so)
-- NumPy ver. 1.11.0 found (include: /usr/lib/python2.7/dist-packages/numpy/core/include)
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- 
-- ******************* Caffe Configuration Summary *******************
-- General:
--   Version           :   1.0.0-rc3
--   Git               :   rc3-120-gb86b0ae
--   System            :   Linux
--   C++ compiler      :   /usr/bin/c++
--   Release CXX flags :   -O3 -DNDEBUG -D_FORCE_INLINES -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Debug CXX flags   :   -g -D_FORCE_INLINES -fPIC -Wall -Wno-sign-compare -Wno-uninitialized
--   Build type        :   Release
-- 
--   BUILD_SHARED_LIBS :   ON
--   BUILD_python      :   ON
--   BUILD_matlab      :   OFF
--   BUILD_docs        :   ON
--   CPU_ONLY          :   OFF
--   USE_OPENCV        :   ON
--   USE_LEVELDB       :   ON
--   USE_LMDB          :   ON
--   ALLOW_LMDB_NOLOCK :   OFF
-- 
-- Dependencies:
--   BLAS              :   Yes (Atlas)
--   Boost             :   Yes (ver. 1.58)
--   glog              :   Yes
--   gflags            :   Yes
--   protobuf          :   Yes (ver. 2.6.1)
--   lmdb              :   Yes (ver. 0.9.17)
--   LevelDB           :   Yes (ver. 1.18)
--   Snappy            :   Yes (ver. 1.1.3)
--   OpenCV            :   Yes (ver. 3.1.0)
--   CUDA              :   Yes (ver. 7.5)
-- 
-- NVIDIA CUDA:
--   Target GPU(s)     :   Auto
--   GPU arch(s)       :   sm_35 sm_21
--   cuDNN             :   Yes (ver. 4.0.7)
-- 
-- Python:
--   Interpreter       :   /usr/bin/python2.7 (ver. 2.7.11)
--   Libraries         :   /usr/lib/x86_64-linux-gnu/libpython2.7.so (ver 2.7.11+)
--   NumPy             :   /usr/lib/python2.7/dist-packages/numpy/core/include (ver 1.11.0)
-- 
-- Documentaion:
--   Doxygen           :   No
--   config_file       :   
-- 
-- Install:
--   Install path      :   /home/icub/robot/tools/caffe/build/install
-- 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/icub/robot/tools/caffe/build
```

**Comment by GiuliaP** [comment]
I think I have sort of reproduced your situation, meaning that at present I have three slightly different configurations, on three machines with a `K40`, and in one of them I am measuring the same computational time as yours. I am now investigating which is the factor that causes the slow down.

In the meantime, I will make some modifications to the module, beyond replacing the `ForwardPrefilled` with `Forward`, `double` precision with `float`, that are a general maintainance of the code (for instance also the `.prototxt` needs to be slightly updated). I think I will open a separate PR for all of these, but let me know if I have to use the one of @Tobias-Fischer .

**Comment by pattacini** [comment]
Thanks @GiuliaP for following up this request.

Regarding the `.prototxt` file, well, my only recommendation is to try to be as general and consistent as possible.

**Comment by Tobias-Fischer** [comment]
Thanks a lot for looking into it @GiuliaP. Please let us know if we can somehow help.
@pattacini: Regarding the `prototxt` file, I guess @GiuliaP just wants to get rid of the deprecated warnings there as well. Maybe it makes sense to force a minimum version of `caffe` in order to avoid having to support multiple versions?

Best, Tobi

**Comment by pattacini** [comment]
@Tobias-Fischer sure if it helps narrow down the required changes.

I see just one caveat: unless we'll manage to solve the performance issue once for good, I'd rather keep support for the current yet old `Caffe` we have now in the lab. If we're lucky enough, future releases will address this sore point and we'll then drop older versions lightheartedly.

**Comment by Tobias-Fischer** [comment]
Well, of course if @GiuliaP finds that the performance drop is definitely due to the new version of `Caffe`, we should instead enforce instead an old version ;).

**Comment by GiuliaP** [comment]
I tried different configurations all day long and I found something but I haven't a clear idea yet.

So far I know that:

1) `caffeCoder` is fast (10ms) with 'old' `caffe` (commit 77ab8f649f78844dfbbd7d91e984428c637df499), both with and without `cuDNN` (the only version which is compatible with the old caffe is `v1`)

2)  `caffeCoder` is slow (let's say, 300ms, like the CPU) with 'new' `caffe` (let's say, commits from end of 2015 on)

3) the measurements reported here (https://github.com/robotology/himrep/pull/10), showing that, when using 'new' `caffe` + `CUDA 7.5` the time is 30ms, and is reduced to 10ms with `float` precision, are confirmed only by a sample code that I had created at the time, that employs `CaffeFeatureExtractor.hpp` to extract features from images stored on disk. But they aren't when running `caffeCoder`, with the same `CaffeFeatureExtractor.hpp` header, on the robot/simulator. In this case indeed the code is slow as specified in point 2)!

Until today, I believed that the times measured with the same identical extraction code (`CaffeFeatureExtractor.cpp`), would have been maintained inside `caffeCoder`. This turns out to be false right now and there must be something which I don't see. This might indicate that it is not a matter of `caffe` but of compatibility between `caffe` and `caffeCoder`.

I'm going to provide you the sample code so that you can try by yourself and maybe understand the issue. In the meantime I'll continue debugging.

**Comment by Tobias-Fischer** [comment]
Hi @GiuliaP,
Just a thought towards the end of the day (I might be totally wrong):
I guess we have the same problem as reported in https://groups.google.com/forum/#!topic/caffe-users/nQGTIx8yqeU There, the issue is that `caffe` is set to GPU mode, but the `Forward()` / `ForwardPrefilled()` is executed from a different thread. As the mode is set thread specific, the `Forward()` method is executed on a thread with CPU mode.
The thread specific feature was introduced in https://github.com/BVLC/caffe/commit/45d792e8b1e44acb467ab9be3debdd9e819c11d1 in August 2015. Thus it makes sense that the old caffe works, but not the new one.
The solution would thus be obviously setting the GPU mode in the same thread as `extract_singleFeat_1D` is called, i.e. in the `onRead()` of the `CaffeCoderPort`.
This would also explain your observation that the very same code works fine with your other example code, as there likely you run the `Forward()` in the same thread as you configure the `CaffeFeatureExtractor`.

I'm sure @pattacini can help us finding the best spot to set the GPU mode, he is the threading expert I've heard :).

Goodnight and I hope to resolve our problem from there,
Tobi

**Comment by pattacini** [comment]
That's been a very good catch @Tobias-Fischer; very likely you got it, thanks a lot!

**Comment by GiuliaP** [comment]
!!!! Right....... Now it's fast! :) We just need to do as you said. Wow, you saved me from another day(s) of work.... Thanks a lot really!!!! I didn't think about this possibility, that in `caffe` the settings are not shared among the threads. But the fact that the time was the same as the CPU only in the `yarp` module was indeed meaningful...

**Comment by pattacini** [comment]
Great team work then!

**Comment by vtikha** [comment]
👍 👍 👍

**Comment by GiuliaP** [comment]
Ok I'm going to provide a PR where I:
- switch to float
- add the `GPU` mode in the feature extraction thread
- upgrade the `.prototxt`
- replace `ForwardPrefilled`

by tonight.

Maybe this can be closed?

**Comment by pattacini** [comment]
@GiuliaP are these changes gonna break back-compatibility?

**Comment by Tobias-Fischer** [comment]
Cool, great to hear the late idea after some wine and a good movie was helpful :+1:

@GiuliaP I look forward to the PR. Let me know if I can help.

@pattacini I vote for breaking back-compatibility. The reasoning behind this is that a proper versioning system was only recently introduced to Caffe, and checking against an unknown version as in https://github.com/robotology/himrep/blob/master/modules/caffeCoder/src/CaffeFeatExtractor.hpp#L21-L33 might work in some cases, but will fail in others. For the future however, now that a versioning system is in place, we should take care of being back-compatible.

**Comment by GiuliaP** [comment]
Totally agree with @Tobias-Fischer .

**Comment by pattacini** [comment]
Ok, but then we need @GiuliaP to upgrade our system to the latest release :smile:

**Comment by GiuliaP** [comment]
Yep, let me first do the PR and check if it breaks back-compatibility. Then, if it breaks (probably yes, due to the `.prototxt` changes), this means that, once we'll pull the new `himrep` on the robot, we'll need also to pull `caffe` in order to compile.

In that situation, if there will be some slowdown even after these fixes, we'll need to upgrade CUDA from 6.5 to 7.5 (maybe drivers) + cuDNN in order to have back the 10ms performance on a brand new system. 

The only thing to be careful is to plan the upgrade when there are no incoming demos. But in any case sooner or later it's something which is necessary.

**Comment by pattacini** [comment]
Agreed :+1:

**Comment by pattacini** [comment]
We can close this issue finally.
Thanks @GiuliaP and @Tobias-Fischer.

**Comment by pattacini** [comment]
@Tobias-Fischer it seems wine helped you hit the [**Ballmer peak**](https://xkcd.com/323/) :smiley:

**Comment by Tobias-Fischer** [comment]
Hahaha :)

**Comment by Tobias-Fischer** [comment]
Re-opening until it's actually solved :)

**Comment by Tobias-Fischer** [comment]
Fixed with https://github.com/robotology/himrep/pull/19
